{% set version = "1.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-batchjobs
  version: {{ version|replace("-", "_") }}

source:
  fn: BatchJobs_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/BatchJobs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/BatchJobs/BatchJobs_{{ version }}.tar.gz
  sha256: 35cc2dae31994b1df982d11939509ce965e12578418c4fbb8cd7a422afd6e4ff

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-bbmisc >=1.9
    - r-dbi
    - r-rsqlite >=1.0.9011
    - r-backports >=1.1.1
    - r-brew
    - r-checkmate >=1.8.0
    - r-data.table >=1.9.6
    - r-digest
    - r-sendmailr
    - r-stringi >=0.4_1
  run:
    - r-base
    - r-bbmisc >=1.9
    - r-dbi
    - r-rsqlite >=1.0.9011
    - r-backports >=1.1.1
    - r-brew
    - r-checkmate >=1.8.0
    - r-data.table >=1.9.6
    - r-digest
    - r-sendmailr
    - r-stringi >=0.4_1

test:
  commands:
    - $R -e "library('BatchJobs')"           # [not win]
    - "\"%R%\" -e \"library('BatchJobs')\""  # [win]

about:
  home: https://github.com/tudo-r/BatchJobs
  license: BSD_2_clause
  summary: Provides Map, Reduce and Filter variants to generate jobs on batch computing systems
    like PBS/Torque, LSF, SLURM and Sun Grid Engine. Multicore and SSH systems are also
    supported. For further details see the project web page.
  license_family: BSD

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
