travis:
  secure:
    BINSTAR_TOKEN: pt9OJybwIaXV/2ieUKWwS2+TTo88UEUKt3YXnYiu/zCReQNPksn9uDks1xdxjYjiDyiGoobhbFF2TU0wE83n1YC6ux42oYUrCbI5QIbmR5UR03TLIaBySsUt6Zaqq9I+6h9mhZWJi6KcwuBof4ZZvB6x1c0lUA33H/1cxIwZlacp6xgCOwOcVDOzl7+/l+3K3o5C1K/R9kkyBSdemFB/XSYU4i9ySnX7c4Fkw3kMbfoEJJVhOb3UImO1vPNDKdejXySMgSn4v6jqBNxygXpVU2Df0NhKZJMWRSvALpxg96oNxF8zlIK8lcAzuU9XtlJWux4PiMZQwY887pLxofh+GoWdiGe3x/8Li54XwaRRYUSbcueVHyYFy3WJWGHczqO9kmhCd2QQ97EcZ6r6HIrNOQWsLRWRpAnUmymHaNYh5XeZbYF7562ctdTXbi+Yv4qF6uVHIaLLQTpjLuWyamJLkwkB4y8W/a30KycZJ0FaUsQLGmPYnUueSp0D9mMUO3SiAq+uImCmLA+jhLnVyJRiMqk+7JsLgUu41X6/DmQUUF9i73aNsETtfv9Qa5+04HjdiLV5kP/R5EEpEpsh9Axcdkzgr8ebqor3+7PrOVxtDB+5EnJWZ7HCK9YYXi7aF8mYVDxFGEkHeJZjVup9PrlnjIspy5/t4jYUPaFRfJwmshk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
