travis:
  secure:
    BINSTAR_TOKEN: f+/ObivNi3jhKEyfPds9DWaGP8204CsJHN9Bl/BYROWffZioGveNX9ivxs6g094x9LAZ+ZbJzwz+fcB54uVyshw7KzRdA5IEi7grEu6HM6Csj9CcfuC8+j9dxkPKF/Yt39j5mOWn9D543F69ycKbr3f/D90J+sJZyUBAlMQL0eGAj9O50LHC4NUrxMLW6jPKGcOmAhBi6uhL8FMX4CcXsnhj1lKN9fGCU/q5YBUvTYOi618LXtvKAJ0Y86kyIuRMUf//MOjZ6WJ9o1FUTat3LUvv9Nsp4qzSEohz6mINvfE8N0ebnlQ5uk3t1tiRgZHrhmoxB+3q/IMXevgQhjMR0Gg33fk2sFiVaRvVqW5W71aMr2HkFHankFlyx51a5W7VNF/NI3C4UE15CLljp1poxOW8J4BAdPKx3dThBUy0i2wDSEn9CKZrwTqlGGs8CQS+JXOO45ol2BE6YxWDdz3mgCYX/9eFaKqpUBJpbyL3VKagcvcD/nZ9glmWXHcYFgm7WysG8bh/QZ71et5TvQCTW2jlxgS/tLiUSgPGgvkS0o/F3dXd44T2VhnO8SCGNss63WEcr6C34R37ainaZwEpDhcwKjZAaOLCKN5PNUtuidUejaeavRBVbi4lP+j0GY3FO5dp6oWnWumYBPdv5xaM0ocTvBpE2snUEZJ4awpnqyQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
