travis:
  secure:
    BINSTAR_TOKEN: nzIIkBmMYhNIlnkhweHXsTg+PyZ9LlBm2ki80YHf9tfw/SBnFR6/fCI121R1u0kOWwKxhJt4VbdBtseP1AXAXRE6KZoBQ3mPRx2re9S7kmczwF0RHpTafmvtqDsy2ABtUQ820Hl4tNaw0S8e/9PPg6enyqu5Y9bdD0iixWd1AZSEa/mdO17UTucoxpHxtXLw07Lz1preHVo/x6YYTrbtJ1265CwLhBAJgDeINZZnOYOZSMg0esghZayCY93785GCCCUpe8obTdgLzZP+BkqmSVfJAS2ggjcJwMXiUvxkH6djf9MYmfE692KHc6Pbq+0AZuXVNQGb9yo8/p11qg6RwzxnFG4IkUeVpqqw1TNru/MGnoGBRlDDdx2CGyLWPPeTSe7QrR0aOe6JjRPMQzKUVTen53xvm0Zrej1474zrBLHd4Q9yX50v/eaNhsc8QYJOH0WwG/xvlRpVxx1GIHEwuxCSKRjxcbKjI8Fxy1TIGpJ2OQrcen4m9rTY+QfyPuvJ38d3oVM0lFIm5Q7zZPSw4IW/atPyX9dlMA9268uZLt+wGR9esrLviFGQGdTEgJHHbqKD6jh/e2Vg8EgHF6AVhmso1OI24zHN69WVd2bd+Vr2zoWUuJVYix3oWmI1yNyaLnhj8QcrjcwCiCxRHAyBF05naDSDx5YXTpMmH1vEFMs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
