appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: MOMtDwLs06rGEZDTf8H6lMTdAVkbMQqkO8k+bcivsYZ1ft1U9jzlijouFmHUcTBqg/Oe6ClS7kkgMJ+6Fppte30Jme0HddTrlOIYRGlWKbKfLCpF+UeSWueU07+1FRse3DJFO8+9BVfgCY6q6A2/SuczBWEgLMnXKHBgaShhdLW/xAOmleMXrHsUxa65vZDGbzKGrWyHiLB7ECn3S8LK/ie4HX9QB2x5iZv9mFsqqXLD7yCeRFBmUe/X7E3Vs/IsxGWd93zmXABhfQx/AAZHvGXDhtSYOQVB2ZpUg+q3X0UA6oKXPT0EqVsm418FhiCzT/JnQ9qYhjHqlI2BjfsTAYceopX4tYpz9wyYXymbwsgkFfp1HIlL7D5MzQPEfdYv7BPc94uW8ZJgkvN3ct8BnKEjbxDzclBrKuphcmPzg3mvXVYWNulvFiUgViJTrI+rRLeY6uE64wJ/7vXujlctf2yNgIJxhFqar/lANNKHaZX87rFFFO+zzhszkqQudKSqsUhmdmg+A2ct+lxBwrNGoJzOg+a9YBbmGsaXbjtEIO8KiIh/6B34bhL1beLyTmGvVIBH0wM8b2gZNKtYU6jdD8H3IvT6L96oLBSy6DovaPeC4puGqRHnQzz/+DA4k4baa3R3vefWR5FCSk8qBZPIN/H07ar0tgQtNgvCRJztw+E=}
bot:
  automerge: true
