travis:
  secure:
    BINSTAR_TOKEN: UsnQ58UfdTjqID5sq9Fq/guW8j6MDz1HqQHFFeKbknq70VcMgGLhefveXfEeUoc3slmCOdagn8cJRR7PhLYGrLfCOgFXO8paNf1J4nZIG0pCcBIK5V+CiyKgkDvyjn6AmRF+OZoVRf5AcbyB5j0f9lK2WeqTxrhr1Inwp2nV54UdXKplXY7IdvKCfSHCx5wRGd0gshL2wKgVHV4XdQX5o328NchfUt04LjiR+qOmwZexlAjhN7HasBbU5nKH/c24Y3nYTx5S0T1rmN5c2A6zJmX22h+GfuWWINL8+G9ZAXeURUOChH6gQDMDxMRx6vweMcNZ5PvV6F/4BDFP1+NX+hbuORQjcgwt2OVlrJ7Aktrfa8BJww7QdaONAzUcnN5vbtHJ10EOGAyh5sTLnyooJrmm+ucAZYBPl308ysMwaogG/9OLGz6wuNYyZg3oOoxN2SmJOhi+Q0DNchVHlkcIyOds1NMZzOlpDtnGgzUoKr3+CQ5aD+kFGfs51Nq7b/vq3Wi1wPh7sbyVPRew0zY23ZP98RKRZlOXaXInVIbNHs4PnvdkQWrcVD9vbcR4FFHXF8ECbDatkGqd7bOCglH1m0GeAKt7ocD1wktuW9eJobymXB+d09YYI1ckvNAfRVLLZP+qotbPyjqz4KOqMPbDx1FcWya0P8MmpH0g4x0HeUY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
